name: Build and Deploy Model Trainer

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  IMAGE_NAME: jusi13/ai-model-train
  MANIFEST_REPO: archi-jusi/argocd-manifest
  MANIFEST_FILE: K8S/AI/ai-model-train-job/values.yaml

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flake8 bandit
          pip install -r src/requirements.txt

      - name: Lint code
        run: flake8 src/ --max-line-length 120

      - name: Security scan
        run: bandit -r src/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          IMAGE_TAG=${BRANCH_NAME}-$(date +%Y%m%d%H%M%S)
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          wget https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Checkout manifest repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO }}
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
          ref: main
          path: manifest-repo

      - name: Update Helm values
        run: |
          cd manifest-repo
          yq e -i ".image.repository = \"${IMAGE_NAME}\"" ${{ env.MANIFEST_FILE }}
          yq e -i ".image.tag = \"${IMAGE_TAG}\"" ${{ env.MANIFEST_FILE }}
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if ! git diff --quiet; then
            git add ${{ env.MANIFEST_FILE }}
            git commit -m "Update image tag to $IMAGE_TAG"
            git push
          else
            echo "No changes to commit"
          fi