name: Build and Deploy Book Model Trainer

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  IMAGE_NAME: jusi13/ai-model-train
  MANIFEST_REPO: archi-jusi/argocd-manifest
  MANIFEST_FILE: K8S/AI/ai-model-train-job/values.yaml
  PYTHON_VERSION: "3.10"
  TRIVY_IGNORE_UNFIXED: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          pip install flake8
          pip install -r src/requirements.txt

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y trivy
    
      - name: Determine Trivy flags
        id: trivy-flags
        run: |
          if [ "${{ env.TRIVY_IGNORE_UNFIXED }}" = "true" ]; then
            echo "flags=--ignore-unfixed" >> $GITHUB_OUTPUT
          else
            echo "flags=" >> $GITHUB_OUTPUT
          fi
      - name: Trivy File System (dependencies) Scan
        run: |
          echo "Running Trivy filesystem scan..."
          trivy fs \
            --scanners vuln,secret,config \
            --severity HIGH,CRITICAL \
            ${{ steps.trivy-flags.outputs.flags }} \
            --exit-code 1 src/ || true

      - name: Run SonarCloud in Docker
        run: |
          docker run --rm \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v "$(pwd)":/usr/src \
            sonarsource/sonar-scanner-cli:5.0.1 \
            -Dsonar.projectKey=ai-model-training \
            -Dsonar.organization=${{ secrets.SONARCLOUDORG }} \
            -Dsonar.sources=src \
            -Dsonar.python.version=${{ env.PYTHON_VERSION }} \
            -Dsonar.host.url=https://sonarcloud.io

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver-opts: network=host

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy Docker Image Scan
        run: |
          echo "üîç Running Trivy image scan..."
          trivy image --severity HIGH,CRITICAL --exit-code 1 ${{ env.IMAGE_NAME }}:latest || true

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          wget https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Checkout manifest repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO }}
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
          ref: main
          path: manifest-repo

      - name: Update Helm values
        run: |
          cd manifest-repo
          yq e -i ".image.repository = \"${IMAGE_NAME}\"" ${{ env.MANIFEST_FILE }}
          yq e -i ".image.tag = \"${IMAGE_TAG}\"" ${{ env.MANIFEST_FILE }}
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if ! git diff --quiet; then
            git add ${{ env.MANIFEST_FILE }}
            git commit -m "Update image tag to $IMAGE_TAG"
            git push
          else
            echo "No changes to commit"
          fi
