name: Build and Deploy Model Trainer

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  IMAGE_NAME: jusi13/ai-model-train
  MANIFEST_REPO: archi-jusi/argocd-manifest
  MANIFEST_FILE: K8S/AI/ai-model-train-job/values.yaml
  PYTHON_VERSION: "3.10"
  ALLOW_BANDIT_FAILURE: true


jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install flake8 bandit
          pip install -r src/requirements.txt

    #   - name: Lint code
    #     run: flake8 src/ --max-line-length 120

      - name: Security scan
        run: |
          echo "Running Bandit security scan..."
          if bandit -r src/; then
            echo "âœ… Bandit passed"
          else
            if [ "${{ env.ALLOW_BANDIT_FAILURE }}" = "true" ]; then
              echo "Bandit found issues, but continuing as allowed."
            else
              echo "Bandit found issues. Failing the pipeline."
              exit 1
            fi
          fi

      - name: Set up Java 17 for SonarCloud
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
            args: >
                -Dsonar.projectKey=ai-model-training
                -Dsonar.organization=Archi-jusi
                -Dsonar.python.version=${{ env.PYTHON_VERSION }}
                -Dsonar.sources=src
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          wget https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Checkout manifest repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFEST_REPO }}
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
          ref: main
          path: manifest-repo

      - name: Update Helm values
        run: |
          cd manifest-repo
          yq e -i ".image.repository = \"${IMAGE_NAME}\"" ${{ env.MANIFEST_FILE }}
          yq e -i ".image.tag = \"${IMAGE_TAG}\"" ${{ env.MANIFEST_FILE }}
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if ! git diff --quiet; then
            git add ${{ env.MANIFEST_FILE }}
            git commit -m "Update image tag to $IMAGE_TAG"
            git push
          else
            echo "No changes to commit"
          fi